---
- name: Set SuSEfirewall2_setup state to firewall_state on SLES 10/11
  service: name=SuSEfirewall2_setup enabled={{firewall_enable}} state={{firewall_state}}
  when: ansible_distribution == 'SLES' and  ansible_distribution_major_version|int  <= 11

- name: Set SuSEfirewall2_init state to firewall_state on SLES 10/11
  service: name=SuSEfirewall2_init enabled={{firewall_enable}} state={{firewall_state}}
  when: ansible_distribution == 'SLES' and  ansible_distribution_major_version|int  <= 11

- name: Set SuSEfirewall2 state to firewall_state on SLES 12
  service: name=SuSEfirewall2 enabled={{firewall_enable}} state={{firewall_state}}
  when: ansible_distribution == 'SLES' and  ansible_distribution_major_version|int  == '12'

- name: Set ip6tables state to firewall_state on RHEL 5/6
  service: name=ip6tables enabled={{firewall_enable}} state={{firewall_state}}
  when: ansible_distribution == 'RedHat' and  ansible_distribution_major_version|int  <= 6

- name: Set iptables state to firewall_state on RHEL 5/6
  service: name=iptables enabled={{firewall_enable}} state={{firewall_state}}
  when: ansible_distribution == 'RedHat' and  ansible_distribution_major_version|int  <= 6

- name: Set firewalld state to firewall_state on RHEL 7
  service: name=firewalld enabled={{firewall_enable}} state={{firewall_state}}
  when: ansible_distribution == 'RedHat' and  ansible_distribution_major_version|int  == '7'
