---
- name: Set ip6tables state to {{firewall_state}} on RHEL 5/6
  service: name=ip6tables enabled={{firewall_enable}} state={{firewall_state}}
  when:
  - ansible_distribution_major_version == '5' or ansible_distribution_major_version == '6'

- name: Set iptables state to {{firewall_state}} on RHEL 5/6
  service: name=iptables enabled={{firewall_enable}} state={{firewall_state}}
  when:
  - ansible_distribution_major_version == '5' or ansible_distribution_major_version == '6'

- name: Set firewalld state to {{firewall_state}} on RHEL 7
  service: name=firewalld enabled={{firewall_enable}} state={{firewall_state}}
  when:
  - ansible_distribution_major_version == '7'
