---
- name: Insert tally controls for Redhat 5 system-auth
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^auth.*required.*pam_tally\.so.*'
              insertafter='^auth.*required.*pam_env'
              line='auth\trequired\tpam_tally.so per_user deny={{fail_deny}} onerr=fail unlock_time={{fail_unlock}}'
              state=present
  when:
  - ansible_distribution_major_version == '5'

- name: Insert tally controls for Redhat 5 system-auth account
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^account.*required.*pam_tally\.so.*'
              insertafter='^account.*required.*pam_unix'
              line='account\trequired\tpam_tally.so'
              state=present
  when:
  - ansible_distribution_major_version == '5'

- name: Insert tally2 controls for RedHat 6 password-auth
  lineinfile: dest=/etc/pam.d/password-auth
              regexp='^auth.*required.*pam_tally.*'
              insertafter='^auth.*required.*pam_env'
              line='auth\trequired\tpam_tally2.so deny={{fail_deny}} onerr=fail unlock_time={{fail_unlock}}'
              state=present
  when:
  - ansible_distribution_major_version == '6'

- name: Insert tally2 controls for RedHat 6 password-auth account
  lineinfile: dest=/etc/pam.d/password-auth
              regexp='^account.*required.*pam_tally.*'
              insertafter='^account.*required.*pam_unix'
              line='account\trequired\tpam_tally2.so'
              state=present
  when:
  - ansible_distribution_major_version == '6'

- name: Insert tally2 controls for RedHat 6 system-auth
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^auth.*required.*pam_tally.*'
              insertafter='^auth.*required.*pam_env'
              line='auth\trequired\tpam_tally2.so deny={{fail_deny}} onerr=fail unlock_time={{fail_unlock}}'
              state=present
  when:
  - ansible_distribution_major_version == '6'

- name: Insert tally2 controls for RedHat 6 system-auth account
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^account.*required.*pam_tally.*'
              insertafter='^account.*required.*pam_unix'
              line='account\trequired\tpam_tally2.so'
              state=present
  when:
  - ansible_distribution_major_version == '6'

- name: Insert faillock controls for RedHat 7 password-auth
  lineinfile: dest=/etc/pam.d/password-auth
              regexp='^auth.*required.*pam_(tally|faillock).*'
              insertafter='^auth.*required.*pam_env'
              line='auth\trequired\tpam_faillock.so preauth deny={{fail_deny}} unlock_time={{fail_unlock}}'
              state=present
  when:
  - ansible_distribution_major_version == '7'

- name: Insert faillock controls for RedHat 7 password-auth account
  lineinfile: dest=/etc/pam.d/password-auth
              regexp='^account.*required.*pam_(tally|faillock).*'
              insertbefore='^account.*required.*pam_unix'
              line='account\trequired\tpam_faillock.so'
              state=present
  when:
  - ansible_distribution_major_version == '7'

- name: Insert faillock controls for RedHat 7 system-auth
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^auth.*required.*pam_(tally|faillock).*'
              insertafter='^auth.*required.*pam_env'
              line='auth\trequired\tpam_faillock.so preauth deny={{fail_deny}} unlock_time={{fail_unlock}}'
              state=present
  when:
  - ansible_distribution_major_version == '7'

- name: Insert faillock controls for RedHat 7 system-auth account
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^account.*required.*pam_(tally|faillock).*'
              insertbefore='^account.*required.*pam_unix'
              line='account\trequired\tpam_faillock.so'
              state=present
  when:
  - ansible_distribution_major_version == '7'

- name: Insert faillock authfail controls for RedHat 7 password-auth
  lineinfile: dest=/etc/pam.d/password-auth
              regexp='^auth.*\[default=die\].*pam_faillock.*'
              insertafter='^auth.*sufficient.*pam_unix'
              line='auth\t[default=die]\tpam_faillock.so authfail audit deny={{fail_deny}} unlock_time={{fail_unlock}}'
              state=present
  when:
  - ansible_distribution_major_version == '7'

- name: Insert faillock authfail controls for RedHat 7 system-auth
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^auth.*\[default=die\].*pam_faillock.*'
              insertafter='^auth.*sufficient.*pam_unix'
              line='auth\t[default=die]\tpam_faillock.so authfail audit deny={{fail_deny}} unlock_time={{fail_unlock}}'
              state=present
  when:
  - ansible_distribution_major_version == '7'

- name: Add unix.so based password history for RedHat 5
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^password.*sufficient.*pam_unix\.so.*'
              insertbefore='^password.*required.*pam_deny'
              line='password\tsufficient\tpam_unix.so sha512 shadow remember={{passhistory}} nullok try_first_pass use_authtok'
              state=present
  when:
  - ansible_distribution_major_version == '5'

- name: Add unix.so based password history for RedHat 6
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^password.*sufficient.*pam_unix\.so.*'
              insertbefore='^password.*required.*pam_deny'
              line='password\tsufficient\tpam_unix.so sha512 shadow remember={{passhistory}} nullok try_first_pass use_authtok'
              state=present
  when:
  - ansible_distribution_major_version == '6'

- name: Remove unix.so based password history for RedHat 7
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^password.*sufficient.*pam_unix\.so.*'
              insertbefore='^password.*required.*pam_deny'
              line='password\tsufficient\tpam_unix.so sha512 shadow nullok try_first_pass use_authtok'
              state=present
  when:
  - ansible_distribution_major_version == '7'

- name: Add pwhistory.so based password history for RedHat 7
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^password.*required.*pam_pwhistory.*'
              insertbefore='^password.*sufficient.*pam_unix'
              line='password\trequired\tpam_pwhistory.so remember={{passhistory}} use_authtok'
              state=present
  when:
  - ansible_distribution_major_version == '7'

- name: configure password complexity for RHEL 5/6
  lineinfile: dest=/etc/pam.d/system-auth
              regexp='^password.*requisite.*pam_cracklib.*'
              insertbefore='^password.*sufficient.*pam_unix'
              line='password\trequisite\tpam_cracklib.so try_first_pass retry=3 minlen={{pwquality_minlen}} dcredit={{pwquality_dcredit}} ucredit={{pwquality_ucredit}} lcredit={{pwquality_lcredit}} ocredit={{pwquality_ocredit}} maxrepeat={{pwquality_maxrepeat}}'
  when:
  - ansible_distribution_major_version == '5' or ansible_distribution_major_version == '6'

- name: create pwquality.conf password complexity configuration for RHEL7
  template: src='pwquality.conf.j2' dest='/etc/security/pwquality.conf' owner=root group=root mode=0644
  when: ansible_distribution_major_version == '7'
